# Generated by Django 4.1.9 on 2023-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_classrooms_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='image',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.com%2Ffree-photos-vectors%2Funknown-profile&psig=AOvVaw3BEosLObllxYBZppLuJOkR&ust=1690007092307000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCMjcvJWVn4ADFQAAAAAdAAAAABAE', upload_to='photo/%Y/%m/%d'),
        ),
    ]
