# Generated by Django 4.1.9 on 2023-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
