# Generated by Django 4.0.1 on 2023-07-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/std.webp', null=True, upload_to='Student_profiles/'),
        ),
    ]