# Generated by Django 4.0.1 on 2023-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footereditpage',
            name='PhoneNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Annauni_num',
            field=models.CharField(default='0000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
